# -*- coding: utf-8 -*-
"""api-flask-dio-jeffersoncampelo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fn_c0L2OnLtbUJssI00xRV9qLDfrhYu-
"""

!pip install flask_ngrok

import pandas as pd
from flask_ngrok import run_with_ngrok
from flask import request, jsonify, Flask
import random as rk

app = Flask(__name__)
run_with_ngrok(app)

d = {
    "name": "Nikla",
    "surname": "Tesla",
    "idade": 60
}

@app.route("/")

def home():
  '''
  The entire line below must be written in a single line.
  '''
  return "<marquee><h3> TO CHECK IN PUT ADD '/input' TO THE URL AND TO CHECK OUT PUT ADD '/output' TO THE URL.</h3></marquee>"

@app.route("/input")

def input():
  return jsonify(d)

@app.route('/output', methods=['GET','POST'])

def predJson():
  pred = r.choice(["positive","negative"])
  nd = d
  nd["prediction"]=pred
  return jsonify(nd)

app.run()